# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alassiqu <alassiqu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/19 15:45:06 by alassiqu          #+#    #+#              #
#    Updated: 2024/01/19 15:45:06 by alassiqu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= push_swap
BONUS	=

CC		= cc
CFLAGS	= -Wall -Wextra -Werror -fsanitize=address

SRCS	= 
OBJS	= $(SRCS:.c=.o)

